// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBC7KsMIb4oX1rJv9Vkt8o20X4Qy4fHtkQ',
    appId: '1:82968260484:web:a0c2d005cd0da3140077d1',
    messagingSenderId: '82968260484',
    projectId: 'flash-chat-5bbf2',
    authDomain: 'flash-chat-5bbf2.firebaseapp.com',
    storageBucket: 'flash-chat-5bbf2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqm4UuN322M85dBISRziFvqUBJ0QoNdh8',
    appId: '1:82968260484:android:9afa6b226e06b0ca0077d1',
    messagingSenderId: '82968260484',
    projectId: 'flash-chat-5bbf2',
    storageBucket: 'flash-chat-5bbf2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB07Kxpwov5bIBs8y81G5rnWtYx-FMjtv0',
    appId: '1:82968260484:ios:4bea9148c10ee9df0077d1',
    messagingSenderId: '82968260484',
    projectId: 'flash-chat-5bbf2',
    storageBucket: 'flash-chat-5bbf2.appspot.com',
    iosBundleId: 'com.example.flashChatNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB07Kxpwov5bIBs8y81G5rnWtYx-FMjtv0',
    appId: '1:82968260484:ios:4bea9148c10ee9df0077d1',
    messagingSenderId: '82968260484',
    projectId: 'flash-chat-5bbf2',
    storageBucket: 'flash-chat-5bbf2.appspot.com',
    iosBundleId: 'com.example.flashChatNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBC7KsMIb4oX1rJv9Vkt8o20X4Qy4fHtkQ',
    appId: '1:82968260484:web:3a009a6549a6aadb0077d1',
    messagingSenderId: '82968260484',
    projectId: 'flash-chat-5bbf2',
    authDomain: 'flash-chat-5bbf2.firebaseapp.com',
    storageBucket: 'flash-chat-5bbf2.appspot.com',
  );

}